export default [
  { id: 'af', name: 'Afghanistan', dial_code: '+93', value: '+93', flag: '🇦🇫' },
  { id: 'al', name: 'Albania', dial_code: '+355', value: '+355', flag: '🇦🇱' },
  { id: 'dz', name: 'Algeria', dial_code: '+213', value: '+213', flag: '🇩🇿' },
  { id: 'ad', name: 'Andorra', dial_code: '+376', value: '+376', flag: '🇦🇩' },
  { id: 'ao', name: 'Angola', dial_code: '+244', value: '+244', flag: '🇦🇴' },
  { id: 'ag', name: 'Antigua and Barbuda', dial_code: '+1-268', value: '+1268', flag: '🇦🇬' },
  { id: 'ar', name: 'Argentina', dial_code: '+54', value: '+54', flag: '🇦🇷' },
  { id: 'am', name: 'Armenia', dial_code: '+374', value: '+374', flag: '🇦🇲' },
  { id: 'au', name: 'Australia', dial_code: '+61', value: '+61', flag: '🇦🇺' },
  { id: 'at', name: 'Austria', dial_code: '+43', value: '+43', flag: '🇦🇹' },
  { id: 'az', name: 'Azerbaijan', dial_code: '+994', value: '+994', flag: '🇦🇿' },
  { id: 'bs', name: 'Bahamas', dial_code: '+1-242', value: '+1242', flag: '🇧🇸' },
  { id: 'bh', name: 'Bahrain', dial_code: '+973', value: '+973', flag: '🇧🇭' },
  { id: 'bd', name: 'Bangladesh', dial_code: '+880', value: '+880', flag: '🇧🇩' },
  { id: 'bb', name: 'Barbados', dial_code: '+1-246', value: '+1246', flag: '🇧🇧' },
  { id: 'by', name: 'Belarus', dial_code: '+375', value: '+375', flag: '🇧🇾' },
  { id: 'be', name: 'Belgium', dial_code: '+32', value: '+32', flag: '🇧🇪' },
  { id: 'bz', name: 'Belize', dial_code: '+501', value: '+501', flag: '🇧🇿' },
  { id: 'bj', name: 'Benin', dial_code: '+229', value: '+229', flag: '🇧🇯' },
  { id: 'bt', name: 'Bhutan', dial_code: '+975', value: '+975', flag: '🇧🇹' },
  { id: 'bo', name: 'Bolivia', dial_code: '+591', value: '+591', flag: '🇧🇴' },
  { id: 'ba', name: 'Bosnia and Herzegovina', dial_code: '+387', value: '+387', flag: '🇧🇦' },
  { id: 'bw', name: 'Botswana', dial_code: '+267', value: '+267', flag: '🇧🇼' },
  { id: 'br', name: 'Brazil', dial_code: '+55', value: '+55', flag: '🇧🇷' },
  { id: 'bn', name: 'Brunei', dial_code: '+673', value: '+673', flag: '🇧🇳' },
  { id: 'bg', name: 'Bulgaria', dial_code: '+359', value: '+359', flag: '🇧🇬' },
  { id: 'bf', name: 'Burkina Faso', dial_code: '+226', value: '+226', flag: '🇧🇫' },
  { id: 'bi', name: 'Burundi', dial_code: '+257', value: '+257', flag: '🇧🇮' },
  { id: 'cv', name: 'Cabo Verde', dial_code: '+238', value: '+238', flag: '🇨🇻' },
  { id: 'kh', name: 'Cambodia', dial_code: '+855', value: '+855', flag: '🇰🇭' },
  { id: 'cm', name: 'Cameroon', dial_code: '+237', value: '+237', flag: '🇨🇲' },
  { id: 'ca', name: 'Canada', dial_code: '+1', value: '+1', flag: '🇨🇦' },
  { id: 'cf', name: 'Central African Republic', dial_code: '+236', value: '+236', flag: '🇨🇫' },
  { id: 'td', name: 'Chad', dial_code: '+235', value: '+235', flag: '🇹🇩' },
  { id: 'cl', name: 'Chile', dial_code: '+56', value: '+56', flag: '🇨🇱' },
  { id: 'cn', name: 'China', dial_code: '+86', value: '+86', flag: '🇨🇳' },
  { id: 'co', name: 'Colombia', dial_code: '+57', value: '+57', flag: '🇨🇴' },
  { id: 'km', name: 'Comoros', dial_code: '+269', value: '+269', flag: '🇰🇲' },
  { id: 'cg', name: 'Congo', dial_code: '+242', value: '+242', flag: '🇨🇬' },
  { id: 'cd', name: 'Congo (DRC)', dial_code: '+243', value: '+243', flag: '🇨🇩' },
  { id: 'cr', name: 'Costa Rica', dial_code: '+506', value: '+506', flag: '🇨🇷' },
  { id: 'hr', name: 'Croatia', dial_code: '+385', value: '+385', flag: '🇭🇷' },
  { id: 'cu', name: 'Cuba', dial_code: '+53', value: '+53', flag: '🇨🇺' },
  { id: 'cy', name: 'Cyprus', dial_code: '+357', value: '+357', flag: '🇨🇾' },
  { id: 'cz', name: 'Czech Republic', dial_code: '+420', value: '+420', flag: '🇨🇿' },
  { id: 'dk', name: 'Denmark', dial_code: '+45', value: '+45', flag: '🇩🇰' },
  { id: 'dj', name: 'Djibouti', dial_code: '+253', value: '+253', flag: '🇩🇯' },
  { id: 'dm', name: 'Dominica', dial_code: '+1-767', value: '+1767', flag: '🇩🇲' },
  { id: 'do', name: 'Dominican Republic', dial_code: '+1-809', value: '+1809', flag: '🇩🇴' },
  { id: 'ec', name: 'Ecuador', dial_code: '+593', value: '+593', flag: '🇪🇨' },
  { id: 'eg', name: 'Egypt', dial_code: '+20', value: '+20', flag: '🇪🇬' },
  { id: 'sv', name: 'El Salvador', dial_code: '+503', value: '+503', flag: '🇸🇻' },
  { id: 'gq', name: 'Equatorial Guinea', dial_code: '+240', value: '+240', flag: '🇬🇶' },
  { id: 'er', name: 'Eritrea', dial_code: '+291', value: '+291', flag: '🇪🇷' },
  { id: 'ee', name: 'Estonia', dial_code: '+372', value: '+372', flag: '🇪🇪' },
  { id: 'et', name: 'Ethiopia', dial_code: '+251', value: '+251', flag: '🇪🇹' },
  { id: 'fj', name: 'Fiji', dial_code: '+679', value: '+679', flag: '🇫🇯' },
  { id: 'fi', name: 'Finland', dial_code: '+358', value: '+358', flag: '🇫🇮' },
  { id: 'fr', name: 'France', dial_code: '+33', value: '+33', flag: '🇫🇷' },
  { id: 'ga', name: 'Gabon', dial_code: '+241', value: '+241', flag: '🇬🇦' },
  { id: 'gm', name: 'Gambia', dial_code: '+220', value: '+220', flag: '🇬🇲' },
  { id: 'ge', name: 'Georgia', dial_code: '+995', value: '+995', flag: '🇬🇪' },
  { id: 'de', name: 'Germany', dial_code: '+49', value: '+49', flag: '🇩🇪' },
  { id: 'gh', name: 'Ghana', dial_code: '+233', value: '+233', flag: '🇬🇭' },
  { id: 'gr', name: 'Greece', dial_code: '+30', value: '+30', flag: '🇬🇷' },
  { id: 'gd', name: 'Grenada', dial_code: '+1-473', value: '+1473', flag: '🇬🇩' },
  { id: 'gt', name: 'Guatemala', dial_code: '+502', value: '+502', flag: '🇬🇹' },
  { id: 'gn', name: 'Guinea', dial_code: '+224', value: '+224', flag: '🇬🇳' },
  { id: 'gw', name: 'Guinea-Bissau', dial_code: '+245', value: '+245', flag: '🇬🇼' },
  { id: 'gy', name: 'Guyana', dial_code: '+592', value: '+592', flag: '🇬🇾' },
  { id: 'ht', name: 'Haiti', dial_code: '+509', value: '+509', flag: '🇭🇹' },
  { id: 'hn', name: 'Honduras', dial_code: '+504', value: '+504', flag: '🇭🇳' },
  { id: 'hk', name: 'Hong Kong', dial_code: '+852', value: '+852', flag: '🇭🇰' },
  { id: 'hu', name: 'Hungary', dial_code: '+36', value: '+36', flag: '🇭🇺' },
  { id: 'is', name: 'Iceland', dial_code: '+354', value: '+354', flag: '🇮🇸' },
  { id: 'in', name: 'India', dial_code: '+91', value: '+91', flag: '🇮🇳' },
  { id: 'id', name: 'Indonesia', dial_code: '+62', value: '+62', flag: '🇮🇩' },
  { id: 'ir', name: 'Iran', dial_code: '+98', value: '+98', flag: '🇮🇷' },
  { id: 'iq', name: 'Iraq', dial_code: '+964', value: '+964', flag: '🇮🇶' },
  { id: 'ie', name: 'Ireland', dial_code: '+353', value: '+353', flag: '🇮🇪' },
  { id: 'il', name: 'Israel', dial_code: '+972', value: '+972', flag: '🇮🇱' },
  { id: 'it', name: 'Italy', dial_code: '+39', value: '+39', flag: '🇮🇹' },
  { id: 'jm', name: 'Jamaica', dial_code: '+1-876', value: '+1876', flag: '🇯🇲' },
  { id: 'jp', name: 'Japan', dial_code: '+81', value: '+81', flag: '🇯🇵' },
  { id: 'jo', name: 'Jordan', dial_code: '+962', value: '+962', flag: '🇯🇴' },
  { id: 'kz', name: 'Kazakhstan', dial_code: '+7', value: '+7', flag: '🇰🇿' },
  { id: 'ke', name: 'Kenya', dial_code: '+254', value: '+254', flag: '🇰🇪' },
  { id: 'ki', name: 'Kiribati', dial_code: '+686', value: '+686', flag: '🇰🇮' },
  { id: 'kw', name: 'Kuwait', dial_code: '+965', value: '+965', flag: '🇰🇼' },
  { id: 'kg', name: 'Kyrgyzstan', dial_code: '+996', value: '+996', flag: '🇰🇬' },
  { id: 'la', name: 'Laos', dial_code: '+856', value: '+856', flag: '🇱🇦' },
  { id: 'lv', name: 'Latvia', dial_code: '+371', value: '+371', flag: '🇱🇻' },
  { id: 'lb', name: 'Lebanon', dial_code: '+961', value: '+961', flag: '🇱🇧' },
  { id: 'ls', name: 'Lesotho', dial_code: '+266', value: '+266', flag: '🇱🇸' },
  { id: 'lr', name: 'Liberia', dial_code: '+231', value: '+231', flag: '🇱🇷' },
  { id: 'ly', name: 'Libya', dial_code: '+218', value: '+218', flag: '🇱🇾' },
  { id: 'li', name: 'Liechtenstein', dial_code: '+423', value: '+423', flag: '🇱🇮' },
  { id: 'lt', name: 'Lithuania', dial_code: '+370', value: '+370', flag: '🇱🇹' },
  { id: 'lu', name: 'Luxembourg', dial_code: '+352', value: '+352', flag: '🇱🇺' },
  { id: 'mo', name: 'Macau', dial_code: '+853', value: '+853', flag: '🇲🇴' },
  { id: 'mg', name: 'Madagascar', dial_code: '+261', value: '+261', flag: '🇲🇬' },
  { id: 'mw', name: 'Malawi', dial_code: '+265', value: '+265', flag: '🇲🇼' },
  { id: 'my', name: 'Malaysia', dial_code: '+60', value: '+60', flag: '🇲🇾' },
  { id: 'mv', name: 'Maldives', dial_code: '+960', value: '+960', flag: '🇲🇻' },
  { id: 'ml', name: 'Mali', dial_code: '+223', value: '+223', flag: '🇲🇱' },
  { id: 'mt', name: 'Malta', dial_code: '+356', value: '+356', flag: '🇲🇹' },
  { id: 'mh', name: 'Marshall Islands', dial_code: '+692', value: '+692', flag: '🇲🇭' },
  { id: 'mr', name: 'Mauritania', dial_code: '+222', value: '+222', flag: '🇲🇷' },
  { id: 'mu', name: 'Mauritius', dial_code: '+230', value: '+230', flag: '🇲🇺' },
  { id: 'mx', name: 'Mexico', dial_code: '+52', value: '+52', flag: '🇲🇽' },
  { id: 'fm', name: 'Micronesia', dial_code: '+691', value: '+691', flag: '🇫🇲' },
  { id: 'md', name: 'Moldova', dial_code: '+373', value: '+373', flag: '🇲🇩' },
  { id: 'mc', name: 'Monaco', dial_code: '+377', value: '+377', flag: '🇲🇨' },
  { id: 'mn', name: 'Mongolia', dial_code: '+976', value: '+976', flag: '🇲🇳' },
  { id: 'me', name: 'Montenegro', dial_code: '+382', value: '+382', flag: '🇲🇪' },
  { id: 'ma', name: 'Morocco', dial_code: '+212', value: '+212', flag: '🇲🇦' },
  { id: 'mz', name: 'Mozambique', dial_code: '+258', value: '+258', flag: '🇲🇿' },
  { id: 'mm', name: 'Myanmar', dial_code: '+95', value: '+95', flag: '🇲🇲' },
  { id: 'na', name: 'Namibia', dial_code: '+264', value: '+264', flag: '🇳🇦' },
  { id: 'nr', name: 'Nauru', dial_code: '+674', value: '+674', flag: '🇳🇷' },
  { id: 'np', name: 'Nepal', dial_code: '+977', value: '+977', flag: '🇳🇵' },
  { id: 'nl', name: 'Netherlands', dial_code: '+31', value: '+31', flag: '🇳🇱' },
  { id: 'nz', name: 'New Zealand', dial_code: '+64', value: '+64', flag: '🇳🇿' },
  { id: 'ni', name: 'Nicaragua', dial_code: '+505', value: '+505', flag: '🇳🇮' },
  { id: 'ne', name: 'Niger', dial_code: '+227', value: '+227', flag: '🇳🇪' },
  { id: 'ng', name: 'Nigeria', dial_code: '+234', value: '+234', flag: '🇳🇬' },
  { id: 'no', name: 'Norway', dial_code: '+47', value: '+47', flag: '🇳🇴' },
  { id: 'om', name: 'Oman', dial_code: '+968', value: '+968', flag: '🇴🇲' },
  { id: 'pk', name: 'Pakistan', dial_code: '+92', value: '+92', flag: '🇵🇰' },
  { id: 'pw', name: 'Palau', dial_code: '+680', value: '+680', flag: '🇵🇼' },
  { id: 'ps', name: 'Palestine', dial_code: '+970', value: '+970', flag: '🇵🇸' },
  { id: 'pa', name: 'Panama', dial_code: '+507', value: '+507', flag: '🇵🇦' },
  { id: 'pg', name: 'Papua New Guinea', dial_code: '+675', value: '+675', flag: '🇵🇬' },
  { id: 'py', name: 'Paraguay', dial_code: '+595', value: '+595', flag: '🇵🇾' },
  { id: 'pe', name: 'Peru', dial_code: '+51', value: '+51', flag: '🇵🇪' },
  { id: 'ph', name: 'Philippines', dial_code: '+63', value: '+63', flag: '🇵🇭' },
  { id: 'pl', name: 'Poland', dial_code: '+48', value: '+48', flag: '🇵🇱' },
  { id: 'pt', name: 'Portugal', dial_code: '+351', value: '+351', flag: '🇵🇹' },
  { id: 'qa', name: 'Qatar', dial_code: '+974', value: '+974', flag: '🇶🇦' },
  { id: 'ro', name: 'Romania', dial_code: '+40', value: '+40', flag: '🇷🇴' },
  { id: 'ru', name: 'Russia', dial_code: '+7', value: '+7', flag: '🇷🇺' },
  { id: 'rw', name: 'Rwanda', dial_code: '+250', value: '+250', flag: '🇷🇼' },
  { id: 'kn', name: 'Saint Kitts and Nevis', dial_code: '+1-869', value: '+1869', flag: '🇰🇳' },
  { id: 'lc', name: 'Saint Lucia', dial_code: '+1-758', value: '+1758', flag: '🇱🇨' },
  { id: 'vc', name: 'Saint Vincent and the Grenadines', dial_code: '+1-784', value: '+1784', flag: '🇻🇨' },
  { id: 'ws', name: 'Samoa', dial_code: '+685', value: '+685', flag: '🇼🇸' },
  { id: 'sm', name: 'San Marino', dial_code: '+378', value: '+378', flag: '🇸🇲' },
  { id: 'st', name: 'Sao Tome and Principe', dial_code: '+239', value: '+239', flag: '🇸🇹' },
  { id: 'sa', name: 'Saudi Arabia', dial_code: '+966', value: '+966', flag: '🇸🇦' },
  { id: 'sn', name: 'Senegal', dial_code: '+221', value: '+221', flag: '🇸🇳' },
  { id: 'rs', name: 'Serbia', dial_code: '+381', value: '+381', flag: '🇷🇸' },
  { id: 'sc', name: 'Seychelles', dial_code: '+248', value: '+248', flag: '🇸🇨' },
  { id: 'sl', name: 'Sierra Leone', dial_code: '+232', value: '+232', flag: '🇸🇱' },
  { id: 'sg', name: 'Singapore', dial_code: '+65', value: '+65', flag: '🇸🇬' },
  { id: 'sk', name: 'Slovakia', dial_code: '+421', value: '+421', flag: '🇸🇰' },
  { id: 'si', name: 'Slovenia', dial_code: '+386', value: '+386', flag: '🇸🇮' },
  { id: 'sb', name: 'Solomon Islands', dial_code: '+677', value: '+677', flag: '🇸🇧' },
  { id: 'so', name: 'Somalia', dial_code: '+252', value: '+252', flag: '🇸🇴' },
  { id: 'za', name: 'South Africa', dial_code: '+27', value: '+27', flag: '🇿🇦' },
  { id: 'ss', name: 'South Sudan', dial_code: '+211', value: '+211', flag: '🇸🇸' },
  { id: 'es', name: 'Spain', dial_code: '+34', value: '+34', flag: '🇪🇸' },
  { id: 'lk', name: 'Sri Lanka', dial_code: '+94', value: '+94', flag: '🇱🇰' },
  { id: 'sd', name: 'Sudan', dial_code: '+249', value: '+249', flag: '🇸🇩' },
  { id: 'sr', name: 'Suriname', dial_code: '+597', value: '+597', flag: '🇸🇷' },
  { id: 'se', name: 'Sweden', dial_code: '+46', value: '+46', flag: '🇸🇪' },
  { id: 'ch', name: 'Switzerland', dial_code: '+41', value: '+41', flag: '🇨🇭' },
  { id: 'sy', name: 'Syria', dial_code: '+963', value: '+963', flag: '🇸🇾' },
  { id: 'tw', name: 'Taiwan', dial_code: '+886', value: '+886', flag: '🇹🇼' },
  { id: 'tj', name: 'Tajikistan', dial_code: '+992', value: '+992', flag: '🇹🇯' },
  { id: 'tz', name: 'Tanzania', dial_code: '+255', value: '+255', flag: '🇹🇿' },
  { id: 'th', name: 'Thailand', dial_code: '+66', value: '+66', flag: '🇹🇭' },
  { id: 'tl', name: 'Timor-Leste', dial_code: '+670', value: '+670', flag: '🇹🇱' },
  { id: 'tg', name: 'Togo', dial_code: '+228', value: '+228', flag: '🇹🇬' },
  { id: 'to', name: 'Tonga', dial_code: '+676', value: '+676', flag: '🇹🇴' },
  { id: 'tt', name: 'Trinidad and Tobago', dial_code: '+1-868', value: '+1868', flag: '🇹🇹' },
  { id: 'tn', name: 'Tunisia', dial_code: '+216', value: '+216', flag: '🇹🇳' },
  { id: 'tr', name: 'Turkey', dial_code: '+90', value: '+90', flag: '🇹🇷' },
  { id: 'tm', name: 'Turkmenistan', dial_code: '+993', value: '+993', flag: '🇹🇲' },
  { id: 'tv', name: 'Tuvalu', dial_code: '+688', value: '+688', flag: '🇹🇻' },
  { id: 'ug', name: 'Uganda', dial_code: '+256', value: '+256', flag: '🇺🇬' },
  { id: 'ua', name: 'Ukraine', dial_code: '+380', value: '+380', flag: '🇺🇦' },
  { id: 'ae', name: 'United Arab Emirates', dial_code: '+971', value: '+971', flag: '🇦🇪' },
  { id: 'gb', name: 'United Kingdom', dial_code: '+44', value: '+44', flag: '🇬🇧' },
  { id: 'us', name: 'United States', dial_code: '+1', value: '+1', flag: '🇺🇸' },
  { id: 'uy', name: 'Uruguay', dial_code: '+598', value: '+598', flag: '🇺🇾' },
  { id: 'uz', name: 'Uzbekistan', dial_code: '+998', value: '+998', flag: '🇺🇿' },
  { id: 'vu', name: 'Vanuatu', dial_code: '+678', value: '+678', flag: '🇻🇺' },
  { id: 'va', name: 'Vatican City', dial_code: '+379', value: '+379', flag: '🇻🇦' },
  { id: 've', name: 'Venezuela', dial_code: '+58', value: '+58', flag: '🇻🇪' },
  { id: 'vn', name: 'Vietnam', dial_code: '+84', value: '+84', flag: '🇻🇳' },
  { id: 'ye', name: 'Yemen', dial_code: '+967', value: '+967', flag: '🇾🇪' },
  { id: 'zm', name: 'Zambia', dial_code: '+260', value: '+260', flag: '🇿🇲' },
  { id: 'zw', name: 'Zimbabwe', dial_code: '+263', value: '+263', flag: '🇿🇼' },
];
